server:
  port: 8080
  servlet:
    context-path: /mcool

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/resources
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    manager:
      jdbc-url: jdbc:mysql://localhost:3306/mcool-manager?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 112233
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立物理连接的个数
      initialSize: 5
      #最小连接池数量
      minIdle: 10
      #最大连接池数量 maxIdle已经不再使用
      maxActive: 200
      #获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validationQuery: select 'x'
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnBorrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: admin
        login-password: admin
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"

    user:
      jdbc-url: jdbc:mysql://localhost:3306/mcool-user?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 112233
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立物理连接的个数
      initialSize: 5
      #最小连接池数量
      minIdle: 10
      #最大连接池数量 maxIdle已经不再使用
      maxActive: 200
      #获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validationQuery: select 'x'
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnBorrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: admin
        login-password: admin
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"
    druid:
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #druid监控配置
      filters: stat,wall,log4j2
      filter:
        commons-log:
          statement-log-enabled: true
          statement-executable-sql-log-enable: true

